// <auto-generated />
namespace ATH.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class listingimagesupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listingimagesupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091515165_listingimagesupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
